# .github/workflows/nextjs.yml

name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # pnpm/action-setup を setup-node の前に追加
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8 # 必要に応じてpnpmのバージョンを指定

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm' # これでpnpmのキャッシュが正しく機能します

      # 手動でのpnpmインストールとPATH設定は不要なため削除

      - name: Install dependencies
        run: pnpm install

      - name: Build with Next.js
        run: pnpm build
      
      # 'pnpm export' は通常 'pnpm build' に含まれるため不要
      # next.config.js で `output: 'export'` を設定してください

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Next.jsのビルド出力ディレクトリを指定
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
